export const EnvironmentVariables = {
    NODE_PATH : process.env.NODE_PATH,
    NEXT_PUBLIC_GOOGLE_CLIENT_ID : process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
    NEXT_PUBLIC_LOCAL_SAVE_MAX_LEN: process.env.NEXT_PUBLIC_LOCAL_SAVE_MAX_LEN,
    NEXT_PUBLIC_SERVER_URL: process.env.NEXT_PUBLIC_SERVER_URL,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
}